# Generated by Django 6.1 on 2026-08-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicituddueno',
            old_name='nombre_complejo',
            new_name='nombre_cancha',
        ),
        migrations.RemoveField(
            model_name='solicituddueno',
            name='instagram_web',
        ),
    ]
